- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['apt-transport-https','build-essential','ca-certificates','curl','git','python-pip', 'python3-venv']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
