- hosts: localhost
  vars_files:
    - host_vars/sds-infra-vars.yaml
  gather_facts: true

  roles:
    - role: sds-infra-common
    - role: sds-infra-volume
    - role: sds-infra-security-group
    - role: sds-infra-instances
